### ISSUE TITLE
improve list

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_html_completion#11]
в списке

- не показывай . + ..
- сортируй папки вверх
- сортируй все по алфавиту
- некрасиво без префикса - голый список- надо префикс
LIST_PREFIX = 'image'

**Comment by Artem3213212** [comment]
. убрать можно но .. (я считаю) оставить надо

**Comment by Artem3213212** [comment]
и ещё \ есть только у папок (по аналогии с linux консолью)

**Comment by Alexey-T** [comment]
а зачем юзеру выбирать пункт .. ? если реализуем перевызов списка- то да.

**Comment by Alexey-T** [comment]
надо 2 префикса
PREFIX_PIC = 'image'
PREFIX_DIR = 'folder'

**Comment by Artem3213212** [comment]
нажать ctrl+space второй раз

**Comment by Alexey-T** [comment]
я доработаю АПИ чтобы не нажимать второй раз
