### ISSUE TITLE
Idea for dirs

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_html_completion#13]
Показать папки в списке это не то- зачем юзеру папку вставлять.
надо вставлять файл картинки.
можно так- сканируй все папки на 1 уровень вниз,
и показывай все картинки из . и всех этих папок.
причем картинки из папок в конце списка.
типа так-

pic1
pic2
pic10
dir2/pic1
dir5/pic2
dir6/pic3

папки в конце но все равно сортировано.

**Comment by Artem3213212** [comment]
не очень т.к. при большом кол-ве файлов внутри папок будет трудно что-либо найти

**Comment by Alexey-T** [comment]
Еще идея. перед ed.complete ты подписываешься на евент on_change,
юзер вставляет имя - ты ловиш евент.
проверяешь что поймал его именно для того же файла. (он прийдет и для другого)
отписываешься от евента.
проверяешь что юзер вставил именно папку. (dir1/ )
и тогда ты вызываешь ed.cmd(cmd_AutoComplete) чтобы был выбор картинки из этой папки
