### ISSUE TITLE
try/finally no need

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_html_completion#6]
оно ничего не делает. даже если будет except..... в плагинах по моему оно не надо.

**Comment by Artem3213212** [comment]
надо чтобы если папка неверная ошибки в консоль не сыпались

**Comment by Artem3213212** [comment]
заменил на except

**Comment by Alexey-T** [comment]
try-except это совсем другое.

**Comment by Alexey-T** [comment]
лучше добавить if os.path.isdir(fn) ?
